<?php

namespace Events;

use App\Events\DownloadFileEvent;
use Illuminate\Support\Facades\Event;
use Tests\TestCase;

/**
 *
 */
class DownloadFileEventTest extends TestCase
{
    /**
     * @var
     */
    protected $user;

    /**
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = $this->createUser();
    }

    /**
     * @return void
     */
    public function test_download_event_dispatched_test()
    {
        Event::fake();
        $user = $this->user;
        Event::dispatch(new DownloadFileEvent($user));
        Event::assertDispatched(DownloadFileEvent::class, function ($event) use ($user) {
            return $event->user->id = $user->id;
        });
    }

    public function test_download_event_not_dispatched_test()
    {
        Event::fake();
        $user = $this->user;
        Event::assertNotDispatched(DownloadFileEvent::class, function ($event) use ($user) {
            return $event->user->id = $user->id;
        });
    }

}
